project:
  title: "Quarto - Template" # É interessante mudar o nome do projeto para gestão de conhecimento
  output-dir: resultados/


lang: pt
format: 
  pdf:
    geometry: 
      - left=3cm 
      - right=2cm 
      - top=3cm 
      - bottom=2cm 
    documentclass: estat/estat
    toc: true
    toc-title: "Sumário"
    mainfont: Arial 
    
    linkcolor: black 
    filecolor: black
    citecolor: black
    urlcolor: black 
    number-sections: true
    
    fig-width: 6.2
    fig-height: 3.66

cap-location: top
fig-pos: H

crossref: 
  fig-title: Figura
  tbl-title: Tabela
  tbl-prefix: ""
  title-delim: ":"
  custom:
    - kind: float
      key: quad
      latex-env: quadro
      reference-prefix: Teste
      caption-prefix: Quadro
      caption-location: top


execute: 
  message: false
  warning: false
  echo: false
   
  
    

include-in-header:
  - file: arquivos_tex/nome_dos_alocados_e_do_cliente.tex # Arrumando para adicionar os autores e o cliente
  - file: arquivos_tex/outros_detalhes.tex

include-before-body: 
  - file: arquivos_tex/logo.tex
  

